<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TableHajj extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seed_data = [
            // ... (The seed data provided earlier)

            // Data for 'tb_hajj'
            [
                'name' => 'Namira Travel Haji dan Umrah',
                'location' => 'Indonesia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 40000000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://namira.travel/listings/paket-umroh-iktikaf-makkah-30-maret-2024-batch-2-eoowblbgrv',
                'duration' => 15,
                'image' => 'path/to/umrah_image_1.jpg',
            ],
            [
                'name' => 'Rabbani Tour',
                'location' => 'Indonesia',
                'airline' => 'Etihad Airways',
                'category' => 'Umrah',
                'price' => 40000000,
                'rating' => 3,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://rabbanitour.com/',
                'duration' => 9,
                'image' => 'path/to/umrah_image_2.jpg',
            ],
            [
                'name' => 'Alfajr',
                'location' => 'Indonesia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 29000000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://alfajrtour.com/',
                'duration' => 13,
                'image' => 'path/to/umrah_image_3.jpg',
            ],
            [
                'name' => 'El-Gazali',
                'location' => 'Indonesia',
                'airline' => 'Malaysia Airlines',
                'category' => 'Umrah',
                'price' => 31000000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'http://www.elgazalitour.com/',
                'duration' => 12,
                'image' => 'path/to/umrah_image_4.jpg',
            ],
            [
                'name' => 'Alhijaz',
                'location' => 'Indonesia',
                'airline' => 'Garuda Indonesia',
                'category' => 'Umrah',
                'price' => 32000000,
                'rating' => 5,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://alhijazindowisata.co.id/',
                'duration' => 9,
                'image' => 'path/to/umrah_image_5.jpg',
            ],
            [
                'name' => 'Alhijaz Tours dan Travel',
                'location' => 'Indonesia',
                'airline' => 'Garuda Indonesia Saudia',
                'category' => 'Haji Plus',
                'price' => 18000000,
                'rating' => 4,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://alhijazindowisata.co.id/',
                'duration' => 25,
                'image' => 'path/to/haji_image_1.jpg',
            ],
            [
                'name' => 'Alhijaz Tours dan Travel',
                'location' => 'Indonesia',
                'airline' => 'Garuda Indonesia Saudia',
                'category' => 'Haji Plus',
                'price' => 23000000,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://alhijazindowisata.co.id/',
                'duration' => 25,
                'image' => 'path/to/haji_image_2.jpg',
            ],
            [
                'name' => 'Namira Travel Haji dan Umrah',
                'location' => 'Indonesia',
                'airline' => 'Garuda Indonesia Saudia',
                'category' => 'Haji Plus',
                'price' => 23000000,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://namira.travel/listings/haji-khusus-masa-tunggu-5-7-tahun-kuota-kemenag-indonesia-bbjrbm315o',
                'duration' => 25,
                'image' => 'path/to/haji_image_3.jpg',
            ],
            [
                'name' => 'Haramainplus',
                'location' => 'Indonesia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 24000000,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://haramainku.com/',
                'duration' => 30,
                'image' => 'path/to/haji_image_4.jpg',
            ],
            [
                'name' => 'Multazam',
                'location' => 'Indonesia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 33000000,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://www.multazam.co.id/',
                'duration' => 23,
                'image' => 'path/to/haji_image_5.jpg',
            ],
            [
                'name' => 'Khazanah',
                'location' => 'Indonesia',
                'airline' => 'Garuda Indonesia',
                'category' => 'Haji Plus',
                'price' => 36000000,
                'rating' => 4,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://khazanahtour.com/',
                'duration' => 28,
                'image' => 'path/to/haji_image_6.jpg',
            ],
            [
                'name' => 'Cahaya Kakbah Tour Travel',
                'location' => 'Indonesia',
                'airline' => 'Air Asia',
                'category' => 'Umrah',
                'price' => 28800000,
                'rating' => 5,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://cahayakabah.com/listings',
                'duration' => 9,
                'image' => 'path/to/umrah_image_6.jpg',
            ],
            [
                'name' => 'Cahaya Kakbah Tour Travel',
                'location' => 'Indonesia',
                'airline' => 'Qatar Airlines',
                'category' => 'Haji Plus',
                'price' => 164850000,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://cahayakabah.com/listings',
                'duration' => 26,
                'image' => 'path/to/haji_image_7.jpg',
            ],
            [
                'name' => 'Hasuna Tour',
                'location' => 'Indonesia',
                'airline' => 'Garuda Indonesia Saudia',
                'category' => 'Umrah',
                'price' => 40000000,
                'rating' => 3,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://hasuna.co.id/',
                'duration' => 9,
                'image' => 'path/to/umrah_image_7.jpg',
            ],
            [
                'name' => 'An Namiroh Travelindo',
                'location' => 'Indonesia',
                'airline' => 'Batik Air',
                'category' => 'Haji Plus',
                'price' => 197146250,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://namiroh.com/',
                'duration' => 25,
                'image' => 'path/to/haji_image_8.jpg',
            ],
            [
                'name' => 'Ikhlas Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 21141304,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://ikhlas.com/travel/en/gb/middle-east/saudi-arabia/jeddah/umrah-syawal-standard/',
                'duration' => 9,
                'image' => 'path/to/umrah_image_8.jpg',
            ],
            [
                'name' => 'Tabung Haji Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 104990,
                'rating' => 4,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://www.thts.com.my/haji/265',
                'duration' => 30,
                'image' => 'path/to/haji_image_9.jpg',
            ],
            [
                'name' => 'Malaysia Hisar Travel',
                'location' => 'Malaysia',
                'airline' => 'Air Arabia',
                'category' => 'Umrah',
                'price' => 29715000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://www.jomumrah.net/pakej-umrah-september-2023',
                'duration' => 11,
                'image' => 'path/to/umrah_image_9.jpg',
            ],
            [
                'name' => 'Malaysia Hisar Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 32865000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://www.jomumrah.net/pakej-umrah-october-2023',
                'duration' => 11,
                'image' => 'path/to/umrah_image_10.jpg',
            ],
            [
                'name' => 'Malaysia Hisar Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 33915000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://www.jomumrah.net/pakej-umrah-november-2023',
                'duration' => 11,
                'image' => 'path/to/umrah_image_11.jpg',
            ],
            [
                'name' => 'Malaysia Hisar Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 33915000,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://www.jomumrah.net/pakej-umrah-december-2023',
                'duration' => 11,
                'image' => 'path/to/umrah_image_12.jpg',
            ],
            [
                'name' => 'Azzuha',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 201240000,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://pakejhaji.com.my/pakej-haji-makarem/',
                'duration' => 42,
                'image' => 'path/to/haji_image_10.jpg',
            ],
            [
                'name' => 'Ikhlas Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 23460000,
                'rating' => 3,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://ikhlas.com/travel/en/gb/middle-east/saudi-arabia/jeddah/umrah-naaem/',
                'duration' => 9,
                'image' => 'path/to/umrah_image_13.jpg',
            ],
            [
                'name' => 'Tabung Haji Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 165414410,
                'rating' => 4,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://www.thts.com.my/haji/262',
                'duration' => 35,
                'image' => 'path/to/haji_image_11.jpg',
            ],
            [
                'name' => 'Azzuha',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 165414410,
                'rating' => 5,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://pakejhaji.com.my/pakej-haji-shohada/',
                'duration' => 42,
                'image' => 'path/to/haji_image_12.jpg',
            ],
            [
                'name' => 'Tabung Haji Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Haji Plus',
                'price' => 251447110,
                'rating' => 4,
                'description' => 'Haji Plus package description goes here.',
                'link' => 'https://www.thts.com.my/haji/263',
                'duration' => 35,
                'image' => 'path/to/haji_image_13.jpg',
            ],
            [
                'name' => 'Ajwa Travel',
                'location' => 'Malaysia',
                'airline' => 'Malaysia Airlines',
                'category' => 'Umrah',
                'price' => 52587.21,
                'rating' => 5,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://ajwatravel.net/',
                'duration' => 14,
                'image' => 'path/to/umrah_image_14.jpg',
            ],
            [
                'name' => 'Alrohmah Travel',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 21809295.27,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://www.alrohmah.com/',
                'duration' => 12,
                'image' => 'path/to/umrah_image_15.jpg',
            ],
            [
                'name' => 'Almansyur International tours',
                'location' => 'Malaysia',
                'airline' => 'Saudia Airlines',
                'category' => 'Umrah',
                'price' => 27435365,
                'rating' => 4,
                'description' => 'Umrah package description goes here.',
                'link' => 'https://www.amitravel.my/',
                'duration' => 12,
                'image' => 'path/to/umrah_image_16.jpg',
            ],
        ];


        foreach ($seed_data as $data) {
            DB::table('tb_hajj')->insert([
                'name' => $data['name'],
                'location' => $data['location'],
                'airline' => $data['airline'],
                'category' => $data['category'],
                'price' => $data['price'],
                'rating' => $data['rating'],
                'description' => $data['description'],
                'image' => $data['image'],
                'link' => $data['link'],
                'duration' => $data['duration'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }


    }
}
